import * as LodashModule from "lodash";
const _ = require("lodash/lodash.min") as typeof LodashModule;

export const _countBy = _.countBy;
export const _defer = _.defer;
export const _each = _.forEach;
export const _extend = _.extend;
export const _filter = _.filter;
export const _find = _.find;
export const _isArray = _.isArray;
export const _isEqual = _.isEqual;
export const _keys = _.keys;
export const _map = _.map;
export const _mapValues = _.mapValues;
export const _maxBy = _.maxBy;
export const _minBy = _.minBy;
export const _pickBy = _.pickBy;
export const _range = _.range;
export const _uniqWith = _.uniqWith;
export const _uniqBy = _.uniqBy;
export const _zipObject = _.zipObject;
export const _max = _.max;
export const _difference = _.difference;
export const _flatten = _.flatten;
