const _LV_FLEX_COLUMN = 1 << 0;
const _LV_FLEX_WRAP = 1 << 2;
const _LV_FLEX_REVERSE = 1 << 3;

export const LV_LAYOUT_NONE = 0;
export const LV_LAYOUT_FLEX = 1;
export const LV_LAYOUT_GRID = 2;

export const LV_FLEX_FLOW_ROW = 0x00;
export const LV_FLEX_FLOW_COLUMN = _LV_FLEX_COLUMN;
export const LV_FLEX_FLOW_ROW_WRAP = LV_FLEX_FLOW_ROW | _LV_FLEX_WRAP;
export const LV_FLEX_FLOW_ROW_REVERSE = LV_FLEX_FLOW_ROW | _LV_FLEX_REVERSE;
export const LV_FLEX_FLOW_ROW_WRAP_REVERSE =
    LV_FLEX_FLOW_ROW | _LV_FLEX_WRAP | _LV_FLEX_REVERSE;
export const LV_FLEX_FLOW_COLUMN_WRAP = LV_FLEX_FLOW_COLUMN | _LV_FLEX_WRAP;
export const LV_FLEX_FLOW_COLUMN_REVERSE =
    LV_FLEX_FLOW_COLUMN | _LV_FLEX_REVERSE;
export const LV_FLEX_FLOW_COLUMN_WRAP_REVERSE =
    LV_FLEX_FLOW_COLUMN | _LV_FLEX_WRAP | _LV_FLEX_REVERSE;

export const LV_FLEX_ALIGN_START = 0;
export const LV_FLEX_ALIGN_END = 1;
export const LV_FLEX_ALIGN_CENTER = 2;
export const LV_FLEX_ALIGN_SPACE_EVENLY = 3;
export const LV_FLEX_ALIGN_SPACE_AROUND = 4;
export const LV_FLEX_ALIGN_SPACE_BETWEEN = 5;
