#include "images.h"

const ext_img_desc_t images[36] = {
    { "background_1", &img_background_1 },
    { "background_2", &img_background_2 },
    { "background_3", &img_background_3 },
    { "heating_button", &img_heating_button },
    { "heating_button_hoover", &img_heating_button_hoover },
    { "security_button", &img_security_button },
    { "security_button_hoover", &img_security_button_hoover },
    { "lighting_button", &img_lighting_button },
    { "lighting_button_hoover", &img_lighting_button_hoover },
    { "face_0", &img_face_0 },
    { "face_1", &img_face_1 },
    { "face_2", &img_face_2 },
    { "header_menu", &img_header_menu },
    { "button_main", &img_button_main },
    { "save", &img_save },
    { "saved", &img_saved },
    { "temperature_background", &img_temperature_background },
    { "power_background", &img_power_background },
    { "watch", &img_watch },
    { "slider_indicator", &img_slider_indicator },
    { "slider_knob", &img_slider_knob },
    { "garage_arrows", &img_garage_arrows },
    { "garage_arrows_hoover", &img_garage_arrows_hoover },
    { "account_box", &img_account_box },
    { "arrow_account_hoover", &img_arrow_account_hoover },
    { "arrow_account", &img_arrow_account },
    { "checkmark", &img_checkmark },
    { "big_checkmark", &img_big_checkmark },
    { "switch_off", &img_switch_off },
    { "switch_on", &img_switch_on },
    { "light_bulb", &img_light_bulb },
    { "slider_lighting", &img_slider_lighting },
    { "arrow_next_hover", &img_arrow_next_hover },
    { "arrow_prev_hoover", &img_arrow_prev_hoover },
    { "arrow_next", &img_arrow_next },
    { "arrow_prev", &img_arrow_prev },
};
