import "project-editor/features/data/data";
import "project-editor/features/page/page";
import "project-editor/features/style/style";
import "project-editor/features/font/font";
import "project-editor/features/bitmap/bitmap";
import "project-editor/features/action/action";
import "project-editor/features/scpi/scpi";
import "project-editor/features/shortcuts/shortcuts";
import "project-editor/features/extension-definitions/extension-definitions";
